// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: core_service.proto

package core_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateSoldProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSoldProductResponse) Reset() {
	*x = UpdateSoldProductResponse{}
	mi := &file_core_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSoldProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSoldProductResponse) ProtoMessage() {}

func (x *UpdateSoldProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSoldProductResponse.ProtoReflect.Descriptor instead.
func (*UpdateSoldProductResponse) Descriptor() ([]byte, []int) {
	return file_core_service_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateSoldProductResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateSoldProductResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateSoldProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	ProductId     int32                  `protobuf:"varint,2,opt,name=productId,proto3" json:"productId,omitempty"`
	WalletId      int32                  `protobuf:"varint,3,opt,name=walletId,proto3" json:"walletId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSoldProductRequest) Reset() {
	*x = UpdateSoldProductRequest{}
	mi := &file_core_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSoldProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSoldProductRequest) ProtoMessage() {}

func (x *UpdateSoldProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSoldProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateSoldProductRequest) Descriptor() ([]byte, []int) {
	return file_core_service_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateSoldProductRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *UpdateSoldProductRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UpdateSoldProductRequest) GetWalletId() int32 {
	if x != nil {
		return x.WalletId
	}
	return 0
}

var File_core_service_proto protoreflect.FileDescriptor

const file_core_service_proto_rawDesc = "" +
	"\n" +
	"\x12core_service.proto\x12\x04core\"I\n" +
	"\x19UpdateSoldProductResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"n\n" +
	"\x18UpdateSoldProductRequest\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\x05R\aorderId\x12\x1c\n" +
	"\tproductId\x18\x02 \x01(\x05R\tproductId\x12\x1a\n" +
	"\bwalletId\x18\x03 \x01(\x05R\bwalletId2c\n" +
	"\vCoreService\x12T\n" +
	"\x11UpdateSoldProduct\x12\x1e.core.UpdateSoldProductRequest\x1a\x1f.core.UpdateSoldProductResponseB\x0fZ\r/core_serviceb\x06proto3"

var (
	file_core_service_proto_rawDescOnce sync.Once
	file_core_service_proto_rawDescData []byte
)

func file_core_service_proto_rawDescGZIP() []byte {
	file_core_service_proto_rawDescOnce.Do(func() {
		file_core_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_service_proto_rawDesc), len(file_core_service_proto_rawDesc)))
	})
	return file_core_service_proto_rawDescData
}

var file_core_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_core_service_proto_goTypes = []any{
	(*UpdateSoldProductResponse)(nil), // 0: core.UpdateSoldProductResponse
	(*UpdateSoldProductRequest)(nil),  // 1: core.UpdateSoldProductRequest
}
var file_core_service_proto_depIdxs = []int32{
	1, // 0: core.CoreService.UpdateSoldProduct:input_type -> core.UpdateSoldProductRequest
	0, // 1: core.CoreService.UpdateSoldProduct:output_type -> core.UpdateSoldProductResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_service_proto_init() }
func file_core_service_proto_init() {
	if File_core_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_service_proto_rawDesc), len(file_core_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_service_proto_goTypes,
		DependencyIndexes: file_core_service_proto_depIdxs,
		MessageInfos:      file_core_service_proto_msgTypes,
	}.Build()
	File_core_service_proto = out.File
	file_core_service_proto_goTypes = nil
	file_core_service_proto_depIdxs = nil
}
