/*
 * Catering service
 *
 * Auth service.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net"

	loggerconfig "github.com/Alexander-s-Digital-Marketplace/payment-service/internal/config/logger"
	routespkg "github.com/Alexander-s-Digital-Marketplace/payment-service/internal/routes"
	paymentlistener "github.com/Alexander-s-Digital-Marketplace/payment-service/internal/services/payment_service/payment_listener"
	pb "github.com/Alexander-s-Digital-Marketplace/payment-service/internal/services/payment_service/payment_service_gen"
	paymentserviceserver "github.com/Alexander-s-Digital-Marketplace/payment-service/internal/services/payment_service/payment_service_server"
	"github.com/sirupsen/logrus"
	"google.golang.org/grpc"
)

func main() {
	loggerconfig.Init()

	go func() {
		routes := routespkg.ApiHandleFunctions{}
		logrus.Println("Server started")
		router := routespkg.NewRouter(routes)
		log.Fatal(router.Run(":8083"))
	}()

	go func() {
		listener, err := net.Listen("tcp", ":50054")
		if err != nil {
			log.Fatalf("Failed to listen: %v", err)
		}

		grpcServer := grpc.NewServer()

		pb.RegisterPaymentServiceServer(grpcServer, &paymentserviceserver.Server{})

		logrus.Println("gRPC server is running on port :50054")
		if err := grpcServer.Serve(listener); err != nil {
			log.Fatalf("Failed to serve gRPC server: %v", err)
		}
	}()

	go paymentlistener.ListenForPayment()

	select {}

}
