// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: payment_service.proto

package payment_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuyProductRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WalletIdBuyer  int32                  `protobuf:"varint,1,opt,name=walletIdBuyer,proto3" json:"walletIdBuyer,omitempty"`
	WalletIdSeller int32                  `protobuf:"varint,2,opt,name=walletIdSeller,proto3" json:"walletIdSeller,omitempty"`
	ProductPrice   float64                `protobuf:"fixed64,3,opt,name=productPrice,proto3" json:"productPrice,omitempty"`
	ProductId      int32                  `protobuf:"varint,4,opt,name=productId,proto3" json:"productId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BuyProductRequest) Reset() {
	*x = BuyProductRequest{}
	mi := &file_payment_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyProductRequest) ProtoMessage() {}

func (x *BuyProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyProductRequest.ProtoReflect.Descriptor instead.
func (*BuyProductRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{0}
}

func (x *BuyProductRequest) GetWalletIdBuyer() int32 {
	if x != nil {
		return x.WalletIdBuyer
	}
	return 0
}

func (x *BuyProductRequest) GetWalletIdSeller() int32 {
	if x != nil {
		return x.WalletIdSeller
	}
	return 0
}

func (x *BuyProductRequest) GetProductPrice() float64 {
	if x != nil {
		return x.ProductPrice
	}
	return 0
}

func (x *BuyProductRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type BuyProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	OrderId       int32                  `protobuf:"varint,2,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	SellerAddress string                 `protobuf:"bytes,4,opt,name=SellerAddress,proto3" json:"SellerAddress,omitempty"`
	ProductPrice  float64                `protobuf:"fixed64,5,opt,name=productPrice,proto3" json:"productPrice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyProductResponse) Reset() {
	*x = BuyProductResponse{}
	mi := &file_payment_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyProductResponse) ProtoMessage() {}

func (x *BuyProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyProductResponse.ProtoReflect.Descriptor instead.
func (*BuyProductResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{1}
}

func (x *BuyProductResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BuyProductResponse) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *BuyProductResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *BuyProductResponse) GetSellerAddress() string {
	if x != nil {
		return x.SellerAddress
	}
	return ""
}

func (x *BuyProductResponse) GetProductPrice() float64 {
	if x != nil {
		return x.ProductPrice
	}
	return 0
}

type RegisterWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress string                 `protobuf:"bytes,1,opt,name=walletAddress,proto3" json:"walletAddress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWalletRequest) Reset() {
	*x = RegisterWalletRequest{}
	mi := &file_payment_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWalletRequest) ProtoMessage() {}

func (x *RegisterWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWalletRequest.ProtoReflect.Descriptor instead.
func (*RegisterWalletRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterWalletRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

type RegisterWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	WalletId      int32                  `protobuf:"varint,2,opt,name=walletId,proto3" json:"walletId,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWalletResponse) Reset() {
	*x = RegisterWalletResponse{}
	mi := &file_payment_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWalletResponse) ProtoMessage() {}

func (x *RegisterWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWalletResponse.ProtoReflect.Descriptor instead.
func (*RegisterWalletResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterWalletResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RegisterWalletResponse) GetWalletId() int32 {
	if x != nil {
		return x.WalletId
	}
	return 0
}

func (x *RegisterWalletResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateWalletRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OldWalletId      int32                  `protobuf:"varint,1,opt,name=oldWalletId,proto3" json:"oldWalletId,omitempty"`
	NewWalletAddress string                 `protobuf:"bytes,2,opt,name=newWalletAddress,proto3" json:"newWalletAddress,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateWalletRequest) Reset() {
	*x = UpdateWalletRequest{}
	mi := &file_payment_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWalletRequest) ProtoMessage() {}

func (x *UpdateWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWalletRequest.ProtoReflect.Descriptor instead.
func (*UpdateWalletRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateWalletRequest) GetOldWalletId() int32 {
	if x != nil {
		return x.OldWalletId
	}
	return 0
}

func (x *UpdateWalletRequest) GetNewWalletAddress() string {
	if x != nil {
		return x.NewWalletAddress
	}
	return ""
}

type UpdateWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	WalletId      int32                  `protobuf:"varint,2,opt,name=walletId,proto3" json:"walletId,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWalletResponse) Reset() {
	*x = UpdateWalletResponse{}
	mi := &file_payment_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWalletResponse) ProtoMessage() {}

func (x *UpdateWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWalletResponse.ProtoReflect.Descriptor instead.
func (*UpdateWalletResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateWalletResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateWalletResponse) GetWalletId() int32 {
	if x != nil {
		return x.WalletId
	}
	return 0
}

func (x *UpdateWalletResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      int32                  `protobuf:"varint,1,opt,name=walletId,proto3" json:"walletId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_payment_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetBalanceRequest) GetWalletId() int32 {
	if x != nil {
		return x.WalletId
	}
	return 0
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Balance       float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_payment_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetBalanceResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetBalanceResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetBalanceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      int32                  `protobuf:"varint,1,opt,name=walletId,proto3" json:"walletId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletRequest) Reset() {
	*x = GetWalletRequest{}
	mi := &file_payment_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletRequest) ProtoMessage() {}

func (x *GetWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletRequest.ProtoReflect.Descriptor instead.
func (*GetWalletRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetWalletRequest) GetWalletId() int32 {
	if x != nil {
		return x.WalletId
	}
	return 0
}

type GetWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Wallet        string                 `protobuf:"bytes,2,opt,name=wallet,proto3" json:"wallet,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletResponse) Reset() {
	*x = GetWalletResponse{}
	mi := &file_payment_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletResponse) ProtoMessage() {}

func (x *GetWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletResponse.ProtoReflect.Descriptor instead.
func (*GetWalletResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetWalletResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetWalletResponse) GetWallet() string {
	if x != nil {
		return x.Wallet
	}
	return ""
}

func (x *GetWalletResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_payment_service_proto protoreflect.FileDescriptor

const file_payment_service_proto_rawDesc = "" +
	"\n" +
	"\x15payment_service.proto\x12\apayment\"\xa3\x01\n" +
	"\x11BuyProductRequest\x12$\n" +
	"\rwalletIdBuyer\x18\x01 \x01(\x05R\rwalletIdBuyer\x12&\n" +
	"\x0ewalletIdSeller\x18\x02 \x01(\x05R\x0ewalletIdSeller\x12\"\n" +
	"\fproductPrice\x18\x03 \x01(\x01R\fproductPrice\x12\x1c\n" +
	"\tproductId\x18\x04 \x01(\x05R\tproductId\"\xa6\x01\n" +
	"\x12BuyProductResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\aOrderId\x18\x02 \x01(\x05R\aOrderId\x12\x18\n" +
	"\aAddress\x18\x03 \x01(\tR\aAddress\x12$\n" +
	"\rSellerAddress\x18\x04 \x01(\tR\rSellerAddress\x12\"\n" +
	"\fproductPrice\x18\x05 \x01(\x01R\fproductPrice\"=\n" +
	"\x15RegisterWalletRequest\x12$\n" +
	"\rwalletAddress\x18\x01 \x01(\tR\rwalletAddress\"b\n" +
	"\x16RegisterWalletResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x1a\n" +
	"\bwalletId\x18\x02 \x01(\x05R\bwalletId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"c\n" +
	"\x13UpdateWalletRequest\x12 \n" +
	"\voldWalletId\x18\x01 \x01(\x05R\voldWalletId\x12*\n" +
	"\x10newWalletAddress\x18\x02 \x01(\tR\x10newWalletAddress\"`\n" +
	"\x14UpdateWalletResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x1a\n" +
	"\bwalletId\x18\x02 \x01(\x05R\bwalletId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"/\n" +
	"\x11GetBalanceRequest\x12\x1a\n" +
	"\bwalletId\x18\x01 \x01(\x05R\bwalletId\"\\\n" +
	"\x12GetBalanceResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\".\n" +
	"\x10GetWalletRequest\x12\x1a\n" +
	"\bwalletId\x18\x01 \x01(\x05R\bwalletId\"Y\n" +
	"\x11GetWalletResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x16\n" +
	"\x06wallet\x18\x02 \x01(\tR\x06wallet\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\x83\x03\n" +
	"\x0ePaymentService\x12E\n" +
	"\n" +
	"BuyProduct\x12\x1a.payment.BuyProductRequest\x1a\x1b.payment.BuyProductResponse\x12F\n" +
	"\vGetBallance\x12\x1a.payment.GetBalanceRequest\x1a\x1b.payment.GetBalanceResponse\x12B\n" +
	"\tGetWallet\x12\x19.payment.GetWalletRequest\x1a\x1a.payment.GetWalletResponse\x12Q\n" +
	"\x0eRegisterWallet\x12\x1e.payment.RegisterWalletRequest\x1a\x1f.payment.RegisterWalletResponse\x12K\n" +
	"\fUpdateWallet\x12\x1c.payment.UpdateWalletRequest\x1a\x1d.payment.UpdateWalletResponseB\x12Z\x10/payment_serviceb\x06proto3"

var (
	file_payment_service_proto_rawDescOnce sync.Once
	file_payment_service_proto_rawDescData []byte
)

func file_payment_service_proto_rawDescGZIP() []byte {
	file_payment_service_proto_rawDescOnce.Do(func() {
		file_payment_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_service_proto_rawDesc), len(file_payment_service_proto_rawDesc)))
	})
	return file_payment_service_proto_rawDescData
}

var file_payment_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_payment_service_proto_goTypes = []any{
	(*BuyProductRequest)(nil),      // 0: payment.BuyProductRequest
	(*BuyProductResponse)(nil),     // 1: payment.BuyProductResponse
	(*RegisterWalletRequest)(nil),  // 2: payment.RegisterWalletRequest
	(*RegisterWalletResponse)(nil), // 3: payment.RegisterWalletResponse
	(*UpdateWalletRequest)(nil),    // 4: payment.UpdateWalletRequest
	(*UpdateWalletResponse)(nil),   // 5: payment.UpdateWalletResponse
	(*GetBalanceRequest)(nil),      // 6: payment.GetBalanceRequest
	(*GetBalanceResponse)(nil),     // 7: payment.GetBalanceResponse
	(*GetWalletRequest)(nil),       // 8: payment.GetWalletRequest
	(*GetWalletResponse)(nil),      // 9: payment.GetWalletResponse
}
var file_payment_service_proto_depIdxs = []int32{
	0, // 0: payment.PaymentService.BuyProduct:input_type -> payment.BuyProductRequest
	6, // 1: payment.PaymentService.GetBallance:input_type -> payment.GetBalanceRequest
	8, // 2: payment.PaymentService.GetWallet:input_type -> payment.GetWalletRequest
	2, // 3: payment.PaymentService.RegisterWallet:input_type -> payment.RegisterWalletRequest
	4, // 4: payment.PaymentService.UpdateWallet:input_type -> payment.UpdateWalletRequest
	1, // 5: payment.PaymentService.BuyProduct:output_type -> payment.BuyProductResponse
	7, // 6: payment.PaymentService.GetBallance:output_type -> payment.GetBalanceResponse
	9, // 7: payment.PaymentService.GetWallet:output_type -> payment.GetWalletResponse
	3, // 8: payment.PaymentService.RegisterWallet:output_type -> payment.RegisterWalletResponse
	5, // 9: payment.PaymentService.UpdateWallet:output_type -> payment.UpdateWalletResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_payment_service_proto_init() }
func file_payment_service_proto_init() {
	if File_payment_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_service_proto_rawDesc), len(file_payment_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_service_proto_goTypes,
		DependencyIndexes: file_payment_service_proto_depIdxs,
		MessageInfos:      file_payment_service_proto_msgTypes,
	}.Build()
	File_payment_service_proto = out.File
	file_payment_service_proto_goTypes = nil
	file_payment_service_proto_depIdxs = nil
}
