// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: profile_register_service.proto

package profile_register_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_profile_register_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_profile_register_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_profile_register_service_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	AccountInfoId int32                  `protobuf:"varint,2,opt,name=AccountInfoId,proto3" json:"AccountInfoId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_profile_register_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_profile_register_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_profile_register_service_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Request) GetAccountInfoId() int32 {
	if x != nil {
		return x.AccountInfoId
	}
	return 0
}

var File_profile_register_service_proto protoreflect.FileDescriptor

const file_profile_register_service_proto_rawDesc = "" +
	"\n" +
	"\x1eprofile_register_service.proto\x12\x04auth\"8\n" +
	"\bResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"K\n" +
	"\aRequest\x12\x1a\n" +
	"\bUserName\x18\x01 \x01(\tR\bUserName\x12$\n" +
	"\rAccountInfoId\x18\x02 \x01(\x05R\rAccountInfoId2J\n" +
	"\x16ProfileRegisterService\x120\n" +
	"\x0fProfileRegister\x12\r.auth.Request\x1a\x0e.auth.ResponseB\x1bZ\x19/profile_register_serviceb\x06proto3"

var (
	file_profile_register_service_proto_rawDescOnce sync.Once
	file_profile_register_service_proto_rawDescData []byte
)

func file_profile_register_service_proto_rawDescGZIP() []byte {
	file_profile_register_service_proto_rawDescOnce.Do(func() {
		file_profile_register_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profile_register_service_proto_rawDesc), len(file_profile_register_service_proto_rawDesc)))
	})
	return file_profile_register_service_proto_rawDescData
}

var file_profile_register_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_profile_register_service_proto_goTypes = []any{
	(*Response)(nil), // 0: auth.Response
	(*Request)(nil),  // 1: auth.Request
}
var file_profile_register_service_proto_depIdxs = []int32{
	1, // 0: auth.ProfileRegisterService.ProfileRegister:input_type -> auth.Request
	0, // 1: auth.ProfileRegisterService.ProfileRegister:output_type -> auth.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_profile_register_service_proto_init() }
func file_profile_register_service_proto_init() {
	if File_profile_register_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profile_register_service_proto_rawDesc), len(file_profile_register_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profile_register_service_proto_goTypes,
		DependencyIndexes: file_profile_register_service_proto_depIdxs,
		MessageInfos:      file_profile_register_service_proto_msgTypes,
	}.Build()
	File_profile_register_service_proto = out.File
	file_profile_register_service_proto_goTypes = nil
	file_profile_register_service_proto_depIdxs = nil
}
